### ISSUE TITLE
Occasional recursion error on application launch

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/keystone-api#125]
Randomly and infrequently I get a recursion error when launching the site:
  
  ```bash
$ DEBUG=1 keystone-api runserver

  Traceback (most recent call last):
    File "/home/djperrefort/miniconda3/envs/keystone-api/bin/keystone-api", line 8, in <module>
    sys.exit(main())
    File "/home/djperrefort/Github/pitt-crc/keystone-api/keystone_api/manage.py", line 12, in main
    execute_from_command_line(sys.argv)
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 883, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/home/djperrefort/Github/pitt-crc/keystone-api/keystone_api/main/settings.py", line 27, in <module>
    SECRET_KEY = env.str('SECURE_SECRET_KEY', get_random_secret_key())
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/environ/environ.py", line 213, in str
    value = self.get_value(var, cast=str, default=default)
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/environ/environ.py", line 401, in get_value
    value = self.get_value(value, cast=cast, default=default)
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/environ/environ.py", line 401, in get_value
    value = self.get_value(value, cast=cast, default=default)
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/environ/environ.py", line 401, in get_value
    value = self.get_value(value, cast=cast, default=default)
    [Previous line repeated 976 more times]
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/environ/environ.py", line 388, in get_value
    value = self.ENVIRON[var_name]
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/os.py", line 677, in __getitem__
    value = self._data[self.encodekey(key)]
    File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/os.py", line 756, in encode
    if not isinstance(value, str):
  RecursionError: maximum recursion depth exceeded while calling a Python object
  ``

**Comment by djperrefort** [comment]
Looks like this is an issue in the parsing of the environmental variables by the `django-environ` package:

https://github.com/joke2k/django-environ/issues/60

The issue is closed but the problem persists.
