### ISSUE TITLE
Test suite passes despite connection error

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/keystone-api#142]
The test suite passes despite raising the following error:

```
unavailable: Unknown error
Traceback (most recent call last):
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 459, in _ensure_connection
    return retry_over_time(
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 934, in _connection_factory
    self._connection = self._establish_connection()
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/transport/pyamqp.py", line 203, in establish_connection
    conn.connect()
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/amqp/connection.py", line 324, in connect
    self.transport.connect()
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/amqp/transport.py", line 129, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/amqp/transport.py", line 184, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/health_check/contrib/celery_ping/backends.py", line 15, in check_status
    ping_result = app.control.ping(timeout=timeout)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/celery/app/control.py", line 563, in ping
    return self.broadcast(
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/celery/app/control.py", line 776, in broadcast
    return self.mailbox(conn)._broadcast(
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/pidbox.py", line 330, in _broadcast
    chan = channel or self.connection.default_channel
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 953, in default_channel
    self._ensure_connection(**conn_opts)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 458, in _ensure_connection
    with ctx():
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: [Errno 111] Connection refused
unavailable: Unknown error
Traceback (most recent call last):
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/utils/functional.py", line 32, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 459, in _ensure_connection
    return retry_over_time(
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 934, in _connection_factory
    self._connection = self._establish_connection()
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/transport/pyamqp.py", line 203, in establish_connection
    conn.connect()
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/amqp/connection.py", line 324, in connect
    self.transport.connect()
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/amqp/transport.py", line 129, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/amqp/transport.py", line 184, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/health_check/contrib/celery/backends.py", line 17, in check_status
    result = add.apply_async(
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/celery/app/task.py", line 594, in apply_async
    return app.send_task(
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/celery/app/base.py", line 799, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/celery/app/amqp.py", line 518, in send_task_message
    ret = producer.publish(
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/messaging.py", line 186, in publish
    return _publish(
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 556, in _ensured
    return fun(*args, **kwargs)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/messaging.py", line 195, in _publish
    channel = self.channel
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/messaging.py", line 218, in _get_channel
    channel = self._channel = channel()
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/utils/functional.py", line 34, in __call__
    value = self.__value__ = self.__contract__()
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/messaging.py", line 234, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 953, in default_channel
    self._ensure_connection(**conn_opts)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 458, in _ensure_connection
    with ctx():
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/djperrefort/miniconda3/envs/keystone-api/lib/python3.10/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: [Errno 111] Connection refused
```

The traceback occurs ~12 times back to back when running the tests.

**Comment by djperrefort** [comment]
After a little extra inspection, it looks like these errors are being raised by all three tests in the `tests/audit/test.py` file.
