### ISSUE TITLE
Celery jobs do not run

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/keystone-api#152]
Celery jobs created via the admin panel never run.

**Comment by djperrefort** [comment]
Looking at the debug logs from celery beat it looks like celery beat isn't seeing the database schedule and the `current schedule` is empty:

```bash
celery -A keystone_api.apps.scheduler beat --loglevel DEBUG


 celery beat v5.3.6 (emerald-rush) is starting.
 __    -    ... __   -        _
 LocalTime -> 2024-02-27 14:00:30
 Configuration ->
     . broker -> redis://cache:6379/0
     . loader -> celery.loaders.app.AppLoader
     . scheduler -> celery.beat.PersistentScheduler
     . db -> celerybeat-schedule
     . logfile -> [stderr]@%DEBUG
     . maxinterval -> 5.00 minutes (300s)
 [2024-02-27 14:00:30,773: DEBUG/MainProcess] Setting default socket timeout to 30
 [2024-02-27 14:00:30,773: INFO/MainProcess] beat: Starting...
 [2024-02-27 14:00:30,793: DEBUG/MainProcess] Current schedule:
 
 [2024-02-27 14:00:30,793: DEBUG/MainProcess] beat: Ticking with max interval->5.00 minutes
 [2024-02-27 14:00:30,793: DEBUG/MainProcess] beat: Waking up in 5.00 minutes.
```


Peaking at the [celery beat readme](https://github.com/celery/django-celery-beat) I realized we're missing the scheduler option in the startup command. However, updating the command results in an AppRegistryNotReady error.

```bash
celery -A keystone_api.apps.scheduler beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel DEBUG

...

 celery beat v5.3.6 (emerald-rush) is starting.
 Traceback (most recent call last):
   File "/home/keystone/.local/bin/celery", line 8, in <module>
     sys.exit(main())
              ^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
     sys.exit(_main())
              ^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/celery/bin/celery.py", line 236, in main
     return celery(auto_envvar_prefix="CELERY")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
     return self.main(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
     rv = self.invoke(ctx)
          ^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
     return _process_result(sub_ctx.command.invoke(sub_ctx))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
     return ctx.invoke(self.callback, **ctx.params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
     return __callback(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
     return f(get_current_context(), *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
     return f(ctx, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/celery/bin/beat.py", line 72, in beat
     return beat().run()
            ^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 84, in run
     self.start_scheduler()
   File "/home/keystone/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 104, in start_scheduler
     print(self.banner(service))
           ^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 126, in banner
     c.reset(self.startup_info(service))),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 136, in startup_info
     scheduler = service.get_scheduler(lazy=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/celery/beat.py", line 668, in get_scheduler
     return symbol_by_name(self.scheduler_cls, aliases=aliases)(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/kombu/utils/imports.py", line 59, in symbol_by_name
     module = imp(module_name, package=package, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/home/keystone/.local/lib/python3.11/site-packages/django_celery_beat/schedulers.py", line 19, in <module>
     from .models import (ClockedSchedule, CrontabSchedule, IntervalSchedule,
   File "/home/keystone/.local/lib/python3.11/site-packages/django_celery_beat/models.py", line 78, in <module>
     class SolarSchedule(models.Model):
   File "/home/keystone/.local/lib/python3.11/site-packages/django/db/models/base.py", line 129, in __new__
     app_config = apps.get_containing_app_config(module)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/keystone/.local/lib/python3.11/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
     self.check_apps_ready()
   File "/home/keystone/.local/lib/python3.11/site-packages/django/apps/registry.py", line 138, in check_apps_ready
     raise AppRegistryNotReady("Apps aren't loaded yet.")
 django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
